source/BK06/CH02/RazorPageOverview/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPageOverview.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

source/BK06/CH02/RazorPageOverview/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace RazorPageOverview.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public string changingString { get; set; }

        public void OnGet()
        {
            changingString = "This is the changing string.";
        }

        public void OnPostView1()
        {
            changingString = "The string has changed.";
        }

        public void OnPostView2()
        {
            changingString = "Another Change!";
        }
    }

    public class CodeBehind
    {
        public string aString = "This is a code behind string.";

        public void ChangeString()
        {
            aString = "This string has changed.";
        }
    }
}

source/BK06/CH02/RazorPageOverview/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPageOverview.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

source/BK06/CH02/RazorPageOverview/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@{
    var showString = "This is a string.";
}

@{
    var codeBehind = new CodeBehind();
}

@{
    bool isView1 = Model.changingString == "The string has changed.";
}

@{
    int ViewNumber;
    if (Model.changingString == "This is the changing string.")
        ViewNumber = 0;
    else if (Model.changingString == "The string has changed.")
        ViewNumber = 1;
    else
        ViewNumber = 2;
}

@{
    string[] Colors = 
        { "Red", "Orange", "Yellow", "Green", "Blue", "Violet" };
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>It's @DateTime.Now.ToLongDateString()</p>
    <p id="StringOutput">@showString</p>
    <p id="StringOutput2">@codeBehind.aString</p>
    <p>@Model.changingString</p>
    <form asp-page-handler="view1" method="post">
        <button>Click to Change Text</button>
    </form>
    <form asp-page-handler="view2" method="post">
        <button>Try Another Change</button>
    </form>
    @if(isView1)
    {
        <p>Using View1</p>
    }
    else
    {
        <p>Not Using View1</p>
    }
    @switch(ViewNumber)
    {
        case 0:
            <p>Using Original View</p>
            break;
        case 1:
            <p>Using View 1</p>
            break;
        case 2:
            <p>Using View 2</p>
            break;
        default:
            <p>Unrecognized View</p>
            break;
    }
    <h3>Colors</h3>
    <ul class="text-left">
    @for(var i = 0; i < Colors.Length; i++)
    {
        <li>Color @i is @Colors[i]</li>
    }
    </ul>
    <h3>Colors Using Foreach</h3>
    @{
        int counter = 0;
    }
    <ul class="text-left">
    @foreach(string item in Colors)
    {
        <li>Color @counter is @item</li>
        counter++;
    }
    </ul>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">
        building Web apps with ASP.NET Core
    </a>.</p>
</div>

source/BK06/CH02/RazorPageOverview/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPageOverview</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorPageOverview</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RazorPageOverview - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>